# Builds the project with Maven Wrapper using the 'release' profile and publishes to Maven Central
# ---
# Add the following Github variables
# - CENTRAL_NAMESPACE:      your Sonatype Namespace (scope of User Token)
# Add the following Github secrets from your Secret Manager
# - CENTRAL_TOKEN_USERNAME: your Sonatype User Token User
# - CENTRAL_TOKEN_PASSWORD: your Sonatype User Token Password
# - MAVEN_GPG_PASSPHRASE:   your GPG passphrase
# - MAVEN_GPG_PRIVATE_KEY:  your GPG private key

name: Maven Publish
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: central-api
          server-username: CENTRAL_TOKEN_USERNAME # expects name of env var
          server-password: CENTRAL_TOKEN_PASSWORD # expects name of env var
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # expects name of env var
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Publish to Apache Maven Central
        run: ./mvnw clean deploy -B -e -P release
        env:
          CENTRAL_TOKEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          CENTRAL_TOKEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Finalize Upload
        # https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#1-modify-your-ci-script
        run: |
          token=$(printf "${{ secrets.CENTRAL_TOKEN_USERNAME }}:${{ secrets.CENTRAL_TOKEN_PASSWORD }}" | base64)
          echo "::add-mask::$token"
          curl \
          --request POST \
          --fail-with-body \
          --no-progress-meter \
          --header "Authorization: Bearer ${token}" \
          https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/${{ vars.CENTRAL_NAMESPACE }}
